tinyMCE.addI18n('en.advanced',{
style_select:"Styles",
font_size:"Taille de la police",
fontdefault:"Famille de police",
block:"Format",
paragraph:"Paragraphe",
div:"Div",
address:"Adresse",
pre:"Préformaté",
h1:"Rubrique 1",
h2:"Rubrique 2",
h3:"Rubrique 3",
h4:"Rubrique 4",
h5:"Rubrique 5",
h6:"Rubrique 6",
blockquote:"Blockquote",
code:"Code",
samp:"Exemple de code",
dt:"Terme de définition ",
dd:"Description Définition",
bold_desc:"Hardi (Ctrl+B)",
italic_desc:"Italique (Ctrl+I)",
underline_desc:"Souligner (Ctrl+U)",
striketrough_desc:"Barré",
justifyleft_desc:"Aligner à gauche",
justifycenter_desc:"Aligné au centre",
justifyright_desc:"Aligné à droite",
justifyfull_desc:"Alignez complète",
bullist_desc:"Liste non ordonnée",
numlist_desc:"Liste ordonnée",
outdent_desc:"Diminuer le retrait",
indent_desc:"Tiret",
undo_desc:"Annuler (Ctrl+Z)",
redo_desc:"Refaire (Ctrl+Y)",
link_desc:"Insérer/Editer un lien",
unlink_desc:"Séparer",
image_desc:"Insérer/Editer une image",
cleanup_desc:"Code désordre nettoyage",
code_desc:"Modifier le code HTML Source",
sub_desc:"Indice",
sup_desc:"Exposant",
hr_desc:"Insérez règle horizontale",
removeformat_desc:"Supprimer le formatage",
custom1_desc:"Votre description personnalisée ici",
forecolor_desc:"Choisir la couleur du texte",
backcolor_desc:"Choisir la couleur d'arrière-plan",
charmap_desc:"Insérer un caractère personnalisé",
visualaid_desc:"Directives bascule / éléments invisibles",
anchor_desc:"Insérer/ancrage d'édition",
cut_desc:"Coupe",
copy_desc:"Copie",
paste_desc:"Colle",
image_props_desc:"Propriétés de l'image",
newdocument_desc:"Nouveau document",
help_desc:"Aide",
blockquote_desc:"Blockquote",
clipboard_msg:"Copier/Couper/Coller n'est pas disponible dans Mozilla et Firefox. Voulez-vous plus d'informations?",
path:"Chemin",
newdocument:"Etes-vous sûr que vous voulez effacer tout le contenu?",
toolbar_focus:"Aller à boutons d'outils - Alt + Q, Aller à l'éditeur - Alt-Z, Aller à la trajectoire de l'élément - Alt-X",
more_colors:"Plus de couleurs",

// Accessibility Strings
shortcuts_desc:"Aide à l'accessibilité",
help_shortcut:". Appuyez sur ALT F10 pour barre d'outils. Appuyez sur ALT 0 de l'aide.",
rich_text_area:"Zone de texte riche.",
toolbar:"Barre d'outils"
});
